CREATE TABLE [dbo].[ModelLayers] (
    [LayerId]             BIGINT         NOT NULL IDENTITY,
    [ModelId]             INT            NOT NULL,
    [LayerIdx]            INT            NOT NULL,
    [LayerName]           NVARCHAR (100) NULL,
    [LayerType]           NVARCHAR (50)  NULL,
    [WeightsGeometry]     GEOMETRY       NULL,
    [TensorShape]         NVARCHAR (200) NULL,
    [TensorDtype]         NVARCHAR (20)  NULL DEFAULT N'float32',
    [QuantizationType]    NVARCHAR (20)  NULL,
    [QuantizationScale]   FLOAT (53)     NULL,
    [QuantizationZeroPoint] FLOAT (53)     NULL,
    [Parameters]          NVARCHAR(MAX)  NULL,
    [ParameterCount]      BIGINT         NULL,
    [ZMin]                FLOAT (53)     NULL,
    [ZMax]                FLOAT (53)     NULL,
    [MMin]                FLOAT (53)     NULL,
    [MMax]                FLOAT (53)     NULL,
    [MortonCode]          BIGINT         NULL,
    [PreviewPointCount]   INT            NULL,
    [CacheHitRate]        FLOAT (53)     NULL DEFAULT 0.0E0,
    [AvgComputeTimeMs]    FLOAT (53)     NULL,
    [LayerAtomId]         BIGINT         NULL,
    CONSTRAINT [PK_ModelLayers] PRIMARY KEY CLUSTERED ([LayerId] ASC),
    CONSTRAINT [FK_ModelLayers_Atoms_LayerAtomId] FOREIGN KEY ([LayerAtomId]) REFERENCES [dbo].[Atoms] ([AtomId]) ON DELETE SET NULL,
    CONSTRAINT [FK_ModelLayers_Models_ModelId] FOREIGN KEY ([ModelId]) REFERENCES [dbo].[Models] ([ModelId]) ON DELETE CASCADE
);
