CREATE TABLE [dbo].[AtomEmbeddings] (
    [AtomEmbeddingId]         BIGINT         NOT NULL IDENTITY,
    [AtomId]                  BIGINT         NOT NULL,
    [ModelId]                 INT            NULL,
    [EmbeddingType]           NVARCHAR (128) NOT NULL,
    [Dimension]               INT            NOT NULL DEFAULT 0,
    [EmbeddingVector]         VARBINARY(MAX) NULL,
    [UsesMaxDimensionPadding] BIT            NOT NULL DEFAULT CAST(0 AS BIT),
    [SpatialProjX]            FLOAT (53)     NULL,
    [SpatialProjY]            FLOAT (53)     NULL,
    [SpatialProjZ]            FLOAT (53)     NULL,
    [SpatialGeometry]         GEOMETRY       NULL,
    [SpatialCoarse]           GEOMETRY       NULL,
    [SpatialBucketX]          INT            NULL,
    [SpatialBucketY]          INT            NULL,
    [SpatialBucketZ]          INT            NOT NULL DEFAULT -2147483648,
    [Metadata]                NVARCHAR(MAX)  NULL,
    [CreatedAt]               DATETIME2 (7)  NOT NULL DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT [PK_AtomEmbeddings] PRIMARY KEY CLUSTERED ([AtomEmbeddingId] ASC),
    CONSTRAINT [FK_AtomEmbeddings_Atoms_AtomId] FOREIGN KEY ([AtomId]) REFERENCES [dbo].[Atoms] ([AtomId]) ON DELETE CASCADE,
    CONSTRAINT [FK_AtomEmbeddings_Models_ModelId] FOREIGN KEY ([ModelId]) REFERENCES [dbo].[Models] ([ModelId])
);
