CREATE TABLE [dbo].[ImagePatches] (
    [PatchId]       BIGINT         NOT NULL IDENTITY,
    [ImageId]       BIGINT         NOT NULL,
    [ParentAtomId]  BIGINT         NULL,
    [PatchIndex]    INT            NULL,
    [PatchX]        INT            NOT NULL,
    [PatchY]        INT            NOT NULL,
    [RowIndex]      INT            NULL,
    [ColIndex]      INT            NULL,
    [PatchWidth]    INT            NOT NULL,
    [PatchHeight]   INT            NOT NULL,
    [PatchRegion]   GEOMETRY       NOT NULL,
    [PatchGeometry] GEOMETRY       NULL,
    [PatchEmbedding]VARBINARY(MAX) NULL,
    [DominantColor] GEOMETRY       NULL,
    [MeanIntensity] REAL           NULL,
    [MeanR]         FLOAT          NULL,
    [MeanG]         FLOAT          NULL,
    [MeanB]         FLOAT          NULL,
    [StdIntensity]  REAL           NULL,
    [Variance]      FLOAT          NULL,
    [TenantId]      INT            NOT NULL DEFAULT (0),
    CONSTRAINT [PK_ImagePatches] PRIMARY KEY CLUSTERED ([PatchId] ASC),
    CONSTRAINT [FK_ImagePatches_Images_ImageId] FOREIGN KEY ([ImageId]) REFERENCES [dbo].[Images] ([ImageId]) ON DELETE CASCADE,
    CONSTRAINT [FK_ImagePatches_Atoms] FOREIGN KEY ([ParentAtomId]) REFERENCES [dbo].[Atoms] ([AtomId])
);
