CREATE TABLE [dbo].[InferenceRequests] (
    [InferenceId]             BIGINT         NOT NULL IDENTITY,
    [RequestTimestamp]        DATETIME2 (7)  NOT NULL DEFAULT (SYSUTCDATETIME()),
    [TaskType]                NVARCHAR (50)  NULL,
    [InputData]               NVARCHAR(MAX)  NULL,
    [InputHash]               BINARY (32)    NULL,
    [CorrelationId]           NVARCHAR (MAX) NULL,
    [Status]                  NVARCHAR (MAX) NULL,
    [Confidence]              FLOAT (53)     NULL,
    [ModelsUsed]              NVARCHAR(MAX)  NULL,
    [EnsembleStrategy]        NVARCHAR (50)  NULL,
    [OutputData]              NVARCHAR(MAX)  NULL,
    [OutputMetadata]          NVARCHAR(MAX)  NULL,
    [TotalDurationMs]         INT            NULL,
    [CacheHit]                BIT            NOT NULL DEFAULT CAST(0 AS BIT),
    [UserRating]              TINYINT        NULL,
    [UserFeedback]            NVARCHAR (MAX) NULL,
    [Complexity]              INT            NULL,
    [SlaTier]                 NVARCHAR (50)  NULL,
    [EstimatedResponseTimeMs] INT            NULL,
    [ModelId]                 INT            NULL,
    CONSTRAINT [PK_InferenceRequests] PRIMARY KEY CLUSTERED ([InferenceId] ASC),
    CONSTRAINT [FK_InferenceRequests_Models_ModelId] FOREIGN KEY ([ModelId]) REFERENCES [dbo].[Models] ([ModelId])
);
