CREATE TABLE [dbo].[AudioFrames] (
    [AudioId]           BIGINT         NOT NULL,
    [FrameNumber]       BIGINT         NOT NULL,
    [ParentAtomId]      BIGINT         NULL,
    [FrameIndex]        INT            NULL,
    [TimestampMs]       BIGINT         NOT NULL,
    [StartTimeSec]      FLOAT          NULL,
    [EndTimeSec]        FLOAT          NULL,
    [AmplitudeL]        REAL           NULL,
    [AmplitudeR]        REAL           NULL,
    [RmsAmplitude]      FLOAT          NULL,
    [PeakAmplitude]     FLOAT          NULL,
    [WaveformGeometry]  GEOMETRY       NULL,
    [SpectralCentroid]  REAL           NULL,
    [SpectralRolloff]   REAL           NULL,
    [ZeroCrossingRate]  REAL           NULL,
    [RmsEnergy]         REAL           NULL,
    [Mfcc]              VARBINARY(MAX) NULL,
    [FrameEmbedding]    VECTOR(1998)   NULL,
    [TenantId]          INT            NOT NULL DEFAULT (0),
    CONSTRAINT [PK_AudioFrames] PRIMARY KEY CLUSTERED ([AudioId] ASC, [FrameNumber] ASC),
    CONSTRAINT [FK_AudioFrames_AudioData_AudioId] FOREIGN KEY ([AudioId]) REFERENCES [dbo].[AudioData] ([AudioId]) ON DELETE CASCADE,
    CONSTRAINT [FK_AudioFrames_Atoms] FOREIGN KEY ([ParentAtomId]) REFERENCES [dbo].[Atoms] ([AtomId])
);
