CREATE TABLE [dbo].[InferenceRequest] (
    [InferenceId]             BIGINT         NOT NULL IDENTITY,
    [RequestTimestamp]        DATETIME2 (7)  NOT NULL DEFAULT (SYSUTCDATETIME()),
    [CompletionTimestamp]     DATETIME2 (7)  NULL,
    [TenantId]                INT            NOT NULL DEFAULT 0,
    [TaskType]                NVARCHAR (50)  NULL,
    [InputData]               JSON  NULL,
    [InputHash]               BINARY (32)    NULL,
    [CorrelationId]           NVARCHAR (MAX) NULL,
    [Status]                  NVARCHAR (MAX) NULL,
    [Confidence]              FLOAT (53)     NULL,
    [ModelsUsed]              JSON  NULL,
    [EnsembleStrategy]        NVARCHAR (50)  NULL,
    [OutputData]              JSON  NULL,
    [OutputMetadata]          JSON  NULL,
    [Temperature]             FLOAT (53)     NULL,
    [TopK]                    INT            NULL,
    [TopP]                    FLOAT (53)     NULL,
    [MaxTokens]               INT            NULL,
    [TotalDurationMs]         INT            NULL,
    [CacheHit]                BIT            NOT NULL DEFAULT CAST(0 AS BIT),
    [UserRating]              TINYINT        NULL,
    [UserFeedback]            NVARCHAR (MAX) NULL,
    [Complexity]              INT            NULL,
    [SlaTier]                 NVARCHAR (50)  NULL,
    [EstimatedResponseTimeMs] INT            NULL,
    [ModelId]                 INT            NULL,
    CONSTRAINT [PK_InferenceRequest] PRIMARY KEY CLUSTERED ([InferenceId] ASC),
    CONSTRAINT [FK_InferenceRequests_Models_ModelId] FOREIGN KEY ([ModelId]) REFERENCES [dbo].[Model] ([ModelId])
);
