CREATE TABLE [dbo].[AtomEmbeddings] (
    [AtomEmbeddingId]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [AtomId]            BIGINT         NOT NULL,
    [EmbeddingVector]   VECTOR(1998)   NULL,
    [Dimension]         INT            DEFAULT ((1998)) NOT NULL,
    [SpatialGeometry]   GEOMETRY       NULL,
    [SpatialCoarse]     GEOMETRY       NULL,
    [SpatialProjection3D] GEOMETRY     NULL,
    [SpatialBucket]     INT            NULL,
    [SpatialBucketX]    INT            NULL,
    [SpatialBucketY]    INT            NULL,
    [SpatialBucketZ]    INT            NULL,
    [SpatialProjX]      FLOAT (53)     NULL,
    [SpatialProjY]      FLOAT (53)     NULL,
    [SpatialProjZ]      FLOAT (53)     NULL,
    [ModelId]           INT            NULL,
    [EmbeddingType]     NVARCHAR (50)  DEFAULT ('semantic') NOT NULL,
    [Metadata]          NVARCHAR (MAX) NULL,
    [TenantId]          INT            DEFAULT ((0)) NOT NULL,
    [LastUpdated]       DATETIME2 (7)  DEFAULT (sysutcdatetime()) NOT NULL,
    [LastComputedUtc]   DATETIME2 (7)  NULL,
    [LastAccessedUtc]   DATETIME2 (7)  NULL,
    [CreatedAt]         DATETIME2 (7)  DEFAULT (sysutcdatetime()) NOT NULL,
    CONSTRAINT [PK_AtomEmbeddings] PRIMARY KEY CLUSTERED ([AtomEmbeddingId] ASC),
    CONSTRAINT [FK_AtomEmbeddings_Atoms] FOREIGN KEY ([AtomId]) REFERENCES [dbo].[Atoms] ([AtomId]),
    CONSTRAINT [FK_AtomEmbeddings_Models] FOREIGN KEY ([ModelId]) REFERENCES [dbo].[Models] ([ModelId])
);
