CREATE TABLE dbo.InferenceCache (
    CacheId BIGINT IDENTITY(1,1) NOT NULL,
    CacheKey BINARY(32) NOT NULL,
    ResultAtomId BIGINT NOT NULL,
    ResultPayload VARBINARY(8000),
    ModelId BIGINT NOT NULL,
    Modality NVARCHAR(50) NOT NULL,
    Confidence FLOAT NOT NULL,
    CreatedUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ExpiresUtc DATETIME2 NOT NULL,
    AccessCount INT NOT NULL DEFAULT 1,
    LastAccessUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_InferenceCache PRIMARY KEY CLUSTERED (CacheId),
    CONSTRAINT UQ_InferenceCache_CacheKey UNIQUE (CacheKey),
    CONSTRAINT CK_InferenceCache_Confidence CHECK (Confidence >= 0.0 AND Confidence <= 1.0),
    CONSTRAINT CK_InferenceCache_ExpiresUtc CHECK (ExpiresUtc > CreatedUtc),
    INDEX IX_InferenceCache_CacheKey (CacheKey),
    INDEX IX_InferenceCache_ModelId (ModelId),
    INDEX IX_InferenceCache_ExpiresUtc (ExpiresUtc)
);