CREATE TABLE [dbo].[Atoms] (
    [AtomId]          BIGINT           NOT NULL IDENTITY,
    [ContentHash]     BINARY (32)      NOT NULL,
    [Modality]        NVARCHAR (64)    NOT NULL,
    [Subtype]         NVARCHAR (128)   NULL,
    [SourceUri]       NVARCHAR (1024)  NULL,
    [SourceType]      NVARCHAR (128)   NULL,
    [CanonicalText]   NVARCHAR (MAX)   NULL,
    [Content]         NVARCHAR (MAX)   NULL,
    [ContentType]     NVARCHAR (128)   NULL,
    [PayloadLocator]  NVARCHAR (1024)  NULL,
    [Metadata]        NVARCHAR(MAX)    NULL,
    [CreatedAt]       DATETIME2 (7)    NOT NULL DEFAULT (SYSUTCDATETIME()),
    [CreatedUtc]      DATETIME2 (7)    NOT NULL DEFAULT (SYSUTCDATETIME()),
    [UpdatedAt]       DATETIME2 (7)    NULL,
    [IsActive]        BIT              NOT NULL DEFAULT CAST(1 AS BIT),
    [IsDeleted]       BIT              NOT NULL DEFAULT CAST(0 AS BIT),
    [TenantId]        INT              NOT NULL DEFAULT CAST(0 AS INT),
    [ReferenceCount]  BIGINT           NOT NULL DEFAULT CAST(0 AS BIGINT),
    [SpatialKey]      GEOMETRY         NULL,
    [ComponentStream] VARBINARY (MAX)  NULL,
    CONSTRAINT [PK_Atoms] PRIMARY KEY CLUSTERED ([AtomId] ASC)
);
