CREATE TABLE [dbo].[AtomRelation] (
    [AtomRelationId]   BIGINT        NOT NULL IDENTITY,
    [SourceAtomId]     BIGINT        NOT NULL,
    [TargetAtomId]     BIGINT        NOT NULL,
    [RelationType]     NVARCHAR (128)NOT NULL,
    [SequenceIndex]    INT           NULL,
    [Weight]           REAL          NULL,
    [Importance]       REAL          NULL,
    [Confidence]       REAL          NULL,
    [SpatialBucket]    BIGINT        NULL,
    [SpatialBucketX]   INT           NULL,
    [SpatialBucketY]   INT           NULL,
    [SpatialBucketZ]   INT           NULL,
    [CoordX]           FLOAT         NULL,
    [CoordY]           FLOAT         NULL,
    [CoordZ]           FLOAT         NULL,
    [CoordT]           FLOAT         NULL,
    [CoordW]           FLOAT         NULL,
    [SpatialExpression]GEOMETRY      NULL,
    [Metadata]         JSON NULL,
    [TenantId]         INT           NOT NULL DEFAULT (0),
    [CreatedAt]        DATETIME2 (7) NOT NULL DEFAULT (SYSUTCDATETIME()),
    [ValidFrom]        DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL DEFAULT SYSUTCDATETIME(),
    [ValidTo]          DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL DEFAULT '9999-12-31 23:59:59.9999999',
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo]),
    CONSTRAINT [PK_AtomRelation] PRIMARY KEY CLUSTERED ([AtomRelationId] ASC),
    CONSTRAINT [FK_AtomRelations_Atoms_SourceAtomId] FOREIGN KEY ([SourceAtomId]) REFERENCES [dbo].[Atom] ([AtomId]),
    CONSTRAINT [FK_AtomRelations_Atoms_TargetAtomId] FOREIGN KEY ([TargetAtomId]) REFERENCES [dbo].[Atom] ([AtomId]),
    INDEX [IX_AtomRelation_SourceTarget] NONCLUSTERED ([SourceAtomId], [TargetAtomId]),
    INDEX [IX_AtomRelation_TargetSource] NONCLUSTERED ([TargetAtomId], [SourceAtomId]),
    INDEX [IX_AtomRelation_RelationType] NONCLUSTERED ([RelationType]),
    INDEX [IX_AtomRelation_SequenceIndex] NONCLUSTERED ([SourceAtomId], [SequenceIndex]),
    INDEX [IX_AtomRelation_SpatialBucket] NONCLUSTERED ([SpatialBucket]) INCLUDE ([SourceAtomId], [TargetAtomId], [CoordX], [CoordY], [CoordZ]),
    INDEX [IX_AtomRelation_Tenant] NONCLUSTERED ([TenantId], [RelationType])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[AtomRelations_History]));

