// <auto-generated />
using System;
using Hartonomous.Data;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Hartonomous.Data.Migrations
{
    [DbContext(typeof(HartonomousDbContext))]
    [Migration("20251103094500_EnrichBillingPlans")]
    partial class EnrichBillingPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hartonomous.Core.Entities.Atom", b =>
                {
                    b.Property<long>("AtomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AtomId"));

                    b.Property<string>("CanonicalText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayloadLocator")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("ReferenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("SourceType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceUri")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Point>("SpatialKey")
                        .HasColumnType("geometry");

                    b.Property<string>("Subtype")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AtomId");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("UX_Atoms_ContentHash");

                    b.ToTable("Atoms", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomEmbedding", b =>
                {
                    b.Property<long>("AtomEmbeddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AtomEmbeddingId"));

                    b.Property<long>("AtomId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("Dimension")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("EmbeddingType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<SqlVector<float>?>("EmbeddingVector")
                        .HasColumnType("VECTOR(1998)");

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<Point>("SpatialCoarse")
                        .HasColumnType("geometry");

                    b.Property<Point>("SpatialGeometry")
                        .HasColumnType("geometry");

                    b.Property<bool>("UsesMaxDimensionPadding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("AtomEmbeddingId");

                    b.HasIndex("ModelId");

                    b.HasIndex("AtomId", "EmbeddingType", "ModelId")
                        .HasDatabaseName("IX_AtomEmbeddings_Atom_Model_Type");

                    b.ToTable("AtomEmbeddings", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomEmbeddingComponent", b =>
                {
                    b.Property<long>("AtomEmbeddingComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AtomEmbeddingComponentId"));

                    b.Property<long>("AtomEmbeddingId")
                        .HasColumnType("bigint");

                    b.Property<int>("ComponentIndex")
                        .HasColumnType("int");

                    b.Property<float>("ComponentValue")
                        .HasColumnType("real");

                    b.HasKey("AtomEmbeddingComponentId");

                    b.HasIndex("AtomEmbeddingId", "ComponentIndex")
                        .IsUnique()
                        .HasDatabaseName("UX_AtomEmbeddingComponents_Embedding_Index");

                    b.ToTable("AtomEmbeddingComponents", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomRelation", b =>
                {
                    b.Property<long>("AtomRelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AtomRelationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("SourceAtomId")
                        .HasColumnType("bigint");

                    b.Property<Geometry>("SpatialExpression")
                        .HasColumnType("geometry");

                    b.Property<long>("TargetAtomId")
                        .HasColumnType("bigint");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("AtomRelationId");

                    b.HasIndex("TargetAtomId");

                    b.HasIndex("SourceAtomId", "TargetAtomId", "RelationType")
                        .HasDatabaseName("IX_AtomRelations_Source_Target_Type");

                    b.ToTable("AtomRelations", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomicAudioSample", b =>
                {
                    b.Property<byte[]>("SampleHash")
                        .HasColumnType("BINARY(32)");

                    b.Property<short>("AmplitudeInt16")
                        .HasColumnType("SMALLINT");

                    b.Property<float>("AmplitudeNormalized")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FirstSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("LastReferenced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("ReferenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasDefaultValue(0L);

                    b.HasKey("SampleHash");

                    b.HasIndex("AmplitudeNormalized")
                        .HasDatabaseName("IX_AtomicAudioSamples_AmplitudeNormalized");

                    b.ToTable("AtomicAudioSamples", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomicPixel", b =>
                {
                    b.Property<byte[]>("PixelHash")
                        .HasColumnType("BINARY(32)");

                    b.Property<byte>("A")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT")
                        .HasDefaultValue((byte)255);

                    b.Property<byte>("B")
                        .HasColumnType("TINYINT");

                    b.Property<Point>("ColorPoint")
                        .HasColumnType("GEOMETRY");

                    b.Property<DateTime>("FirstSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte>("G")
                        .HasColumnType("TINYINT");

                    b.Property<DateTime>("LastReferenced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte>("R")
                        .HasColumnType("TINYINT");

                    b.Property<long>("ReferenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasDefaultValue(0L);

                    b.HasKey("PixelHash");

                    b.ToTable("AtomicPixels", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomicTextToken", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TokenId"));

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("FirstSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("LastReferenced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("ReferenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasDefaultValue(0L);

                    b.Property<SqlVector<float>?>("TokenEmbedding")
                        .HasColumnType("VECTOR(768)");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BINARY(32)");

                    b.Property<int>("TokenLength")
                        .HasColumnType("int");

                    b.Property<string>("TokenText")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<int?>("VocabId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TokenText")
                        .IsUnique()
                        .HasDatabaseName("IX_AtomicTextTokens_TokenText");

                    b.ToTable("AtomicTextTokens", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AudioData", b =>
                {
                    b.Property<long>("AudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AudioId"));

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<SqlVector<float>?>("GlobalEmbedding")
                        .HasColumnType("VECTOR(768)");

                    b.Property<int?>("GlobalEmbeddingDim")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IngestionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Geometry>("MelSpectrogram")
                        .HasColumnType("GEOMETRY");

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<byte>("NumChannels")
                        .HasColumnType("tinyint");

                    b.Property<int>("SampleRate")
                        .HasColumnType("int");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Geometry>("Spectrogram")
                        .HasColumnType("GEOMETRY");

                    b.Property<Geometry>("WaveformLeft")
                        .HasColumnType("GEOMETRY");

                    b.Property<Geometry>("WaveformRight")
                        .HasColumnType("GEOMETRY");

                    b.HasKey("AudioId");

                    b.HasIndex("DurationMs")
                        .HasDatabaseName("IX_AudioData_DurationMs");

                    b.HasIndex("IngestionDate")
                        .IsDescending()
                        .HasDatabaseName("IX_AudioData_IngestionDate");

                    b.ToTable("AudioData", "dbo");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AudioFrame", b =>
                {
                    b.Property<long>("AudioId")
                        .HasColumnType("bigint");

                    b.Property<long>("FrameNumber")
                        .HasColumnType("bigint");

                    b.Property<float?>("AmplitudeL")
                        .HasColumnType("real");

                    b.Property<float?>("AmplitudeR")
                        .HasColumnType("real");

                    b.Property<SqlVector<float>?>("FrameEmbedding")
                        .HasColumnType("VECTOR(768)");

                    b.Property<SqlVector<float>?>("Mfcc")
                        .HasColumnType("VECTOR(13)");

                    b.Property<float?>("RmsEnergy")
                        .HasColumnType("real");

                    b.Property<float?>("SpectralCentroid")
                        .HasColumnType("real");

                    b.Property<float?>("SpectralRolloff")
                        .HasColumnType("real");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint");

                    b.Property<float?>("ZeroCrossingRate")
                        .HasColumnType("real");

                    b.HasKey("AudioId", "FrameNumber");

                    b.ToTable("AudioFrames", "dbo");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.BillingMultiplier", b =>
                {
                    b.Property<Guid>("MultiplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("RatePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("MultiplierId");

                    b.HasIndex("RatePlanId", "Dimension", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_BillingMultipliers_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("BillingMultipliers", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.BillingOperationRate", b =>
                {
                    b.Property<Guid>("OperationRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Operation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("RatePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("OperationRateId");

                    b.HasIndex("RatePlanId", "Operation")
                        .IsUnique()
                        .HasDatabaseName("UX_BillingOperationRates_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("BillingOperationRates", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.BillingRatePlan", b =>
                {
                    b.Property<Guid>("RatePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("DefaultRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(0.01m);

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("IncludedPrivateStorageGb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("IncludedPublicStorageGb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("IncludedSeatCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MonthlyFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("");

                    b.Property<decimal>("UnitPricePerDcu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(0.00008m);

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("AllowsPrivateData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanQueryPublicCorpus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("RatePlanId");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("IX_BillingRatePlans_Tenant_IsActive");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "IsActive"), new[] { "UpdatedUtc" });

                    b.HasIndex("TenantId", "PlanCode")
                        .IsUnique()
                        .HasDatabaseName("UX_BillingRatePlans_Tenant_PlanCode")
                        .HasFilter("[PlanCode] <> ''");

                    b.ToTable("BillingRatePlans", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.CachedActivation", b =>
                {
                    b.Property<long>("CacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CacheId"));

                    b.Property<SqlVector<float>?>("ActivationOutput")
                        .HasColumnType("VECTOR(1998)");

                    b.Property<long>("ComputeTimeSavedMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<byte[]>("InputHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)");

                    b.Property<DateTime>("LastAccessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("LayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("OutputShape")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CacheId");

                    b.HasIndex("LayerId");

                    b.HasIndex("LastAccessed", "HitCount")
                        .IsDescending()
                        .HasDatabaseName("IX_CachedActivations_LastAccessed_HitCount");

                    b.HasIndex("ModelId", "LayerId", "InputHash")
                        .IsUnique()
                        .HasDatabaseName("IX_CachedActivations_Model_Layer_InputHash");

                    b.ToTable("CachedActivations", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.DeduplicationPolicy", b =>
                {
                    b.Property<int>("DeduplicationPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeduplicationPolicyId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double?>("SemanticThreshold")
                        .HasColumnType("float");

                    b.Property<double?>("SpatialThreshold")
                        .HasColumnType("float");

                    b.HasKey("DeduplicationPolicyId");

                    b.HasIndex("PolicyName")
                        .IsUnique()
                        .HasDatabaseName("UX_DeduplicationPolicies_PolicyName");

                    b.ToTable("DeduplicationPolicies", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.Embedding", b =>
                {
                    b.Property<long>("EmbeddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmbeddingId"));

                    b.Property<int>("AccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("Dimension")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(768);

                    b.Property<SqlVector<float>?>("EmbeddingFull")
                        .HasColumnType("VECTOR(768)");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastAccessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Point>("SpatialCoarse")
                        .HasColumnType("geometry");

                    b.Property<Point>("SpatialGeometry")
                        .HasColumnType("geometry");

                    b.Property<double?>("SpatialProjX")
                        .HasColumnType("float");

                    b.Property<double?>("SpatialProjY")
                        .HasColumnType("float");

                    b.Property<double?>("SpatialProjZ")
                        .HasColumnType("float");

                    b.HasKey("EmbeddingId");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_Embeddings_Production_ContentHash");

                    b.ToTable("Embeddings_Production", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.GenerationStream", b =>
                {
                    b.Property<Guid>("StreamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("PayloadSizeBytes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("CONVERT(BIGINT, DATALENGTH([Stream]))", true);

                    b.Property<string>("Scope")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("Stream")
                        .IsRequired()
                        .HasColumnType("provenance.AtomicStream");

                    b.HasKey("StreamId")
                        .HasName("PK_GenerationStreams");

                    b.HasIndex("Model")
                        .HasDatabaseName("IX_GenerationStreams_Model");

                    b.HasIndex("Scope")
                        .HasDatabaseName("IX_GenerationStreams_Scope");

                    b.ToTable("GenerationStreams", "provenance");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.Image", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImageId"));

                    b.Property<long>("AccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("Channels")
                        .HasColumnType("int");

                    b.Property<Geometry>("EdgeMap")
                        .HasColumnType("GEOMETRY");

                    b.Property<string>("Format")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<SqlVector<float>?>("GlobalEmbedding")
                        .HasColumnType("VECTOR(1536)");

                    b.Property<int?>("GlobalEmbeddingDim")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IngestionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("LastAccessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<Geometry>("ObjectRegions")
                        .HasColumnType("GEOMETRY");

                    b.Property<Geometry>("PixelCloud")
                        .HasColumnType("GEOMETRY");

                    b.Property<Geometry>("SaliencyRegions")
                        .HasColumnType("GEOMETRY");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("IngestionDate")
                        .IsDescending()
                        .HasDatabaseName("IX_Images_IngestionDate");

                    b.HasIndex("Width", "Height")
                        .HasDatabaseName("IX_Images_Width_Height");

                    b.ToTable("Images", "dbo");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.ImagePatch", b =>
                {
                    b.Property<long>("PatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PatchId"));

                    b.Property<Geometry>("DominantColor")
                        .HasColumnType("GEOMETRY");

                    b.Property<long>("ImageId")
                        .HasColumnType("bigint");

                    b.Property<float?>("MeanIntensity")
                        .HasColumnType("real");

                    b.Property<SqlVector<float>?>("PatchEmbedding")
                        .HasColumnType("VECTOR(768)");

                    b.Property<int>("PatchHeight")
                        .HasColumnType("int");

                    b.Property<Geometry>("PatchRegion")
                        .IsRequired()
                        .HasColumnType("GEOMETRY");

                    b.Property<int>("PatchWidth")
                        .HasColumnType("int");

                    b.Property<int>("PatchX")
                        .HasColumnType("int");

                    b.Property<int>("PatchY")
                        .HasColumnType("int");

                    b.Property<float?>("StdIntensity")
                        .HasColumnType("real");

                    b.HasKey("PatchId");

                    b.HasIndex("ImageId", "PatchX", "PatchY")
                        .HasDatabaseName("IX_ImagePatches_ImageId_PatchX_PatchY");

                    b.ToTable("ImagePatches", "dbo");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.InferenceRequest", b =>
                {
                    b.Property<long>("InferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InferenceId"));

                    b.Property<bool>("CacheHit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("EnsembleStrategy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InputData")
                        .HasColumnType("JSON");

                    b.Property<byte[]>("InputHash")
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("ModelsUsed")
                        .HasColumnType("JSON");

                    b.Property<string>("OutputData")
                        .HasColumnType("JSON");

                    b.Property<string>("OutputMetadata")
                        .HasColumnType("JSON");

                    b.Property<DateTime>("RequestTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("TaskType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TotalDurationMs")
                        .HasColumnType("int");

                    b.Property<string>("UserFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("UserRating")
                        .HasColumnType("tinyint");

                    b.HasKey("InferenceId");

                    b.HasIndex("CacheHit")
                        .HasDatabaseName("IX_InferenceRequests_CacheHit");

                    b.HasIndex("InputHash")
                        .HasDatabaseName("IX_InferenceRequests_InputHash");

                    b.HasIndex("ModelId");

                    b.HasIndex("RequestTimestamp")
                        .IsDescending()
                        .HasDatabaseName("IX_InferenceRequests_RequestTimestamp");

                    b.HasIndex("TaskType")
                        .HasDatabaseName("IX_InferenceRequests_TaskType");

                    b.ToTable("InferenceRequests", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.InferenceStep", b =>
                {
                    b.Property<long>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StepId"));

                    b.Property<bool>("CacheUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("IndexUsed")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("InferenceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LayerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("OperationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QueryText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RowsExamined")
                        .HasColumnType("bigint");

                    b.Property<long?>("RowsReturned")
                        .HasColumnType("bigint");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("StepId");

                    b.HasIndex("ModelId");

                    b.HasIndex("InferenceId", "StepNumber")
                        .HasDatabaseName("IX_InferenceSteps_InferenceId_StepNumber");

                    b.ToTable("InferenceSteps", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.IngestionJob", b =>
                {
                    b.Property<long>("IngestionJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IngestionJobId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<string>("PipelineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceUri")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("IngestionJobId");

                    b.ToTable("IngestionJobs", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.IngestionJobAtom", b =>
                {
                    b.Property<long>("IngestionJobAtomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IngestionJobAtomId"));

                    b.Property<long>("AtomId")
                        .HasColumnType("bigint");

                    b.Property<long>("IngestionJobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("WasDuplicate")
                        .HasColumnType("bit");

                    b.HasKey("IngestionJobAtomId");

                    b.HasIndex("AtomId");

                    b.HasIndex("IngestionJobId", "AtomId")
                        .HasDatabaseName("IX_IngestionJobAtoms_Job_Atom");

                    b.ToTable("IngestionJobAtoms", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("Architecture")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("AverageInferenceMs")
                        .HasColumnType("float");

                    b.Property<string>("Config")
                        .HasColumnType("JSON");

                    b.Property<DateTime>("IngestionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("ParameterCount")
                        .HasColumnType("bigint");

                    b.Property<long>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("ModelId");

                    b.HasIndex("ModelName")
                        .HasDatabaseName("IX_Models_ModelName");

                    b.HasIndex("ModelType")
                        .HasDatabaseName("IX_Models_ModelType");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.ModelLayer", b =>
                {
                    b.Property<long>("LayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LayerId"));

                    b.Property<double?>("AvgComputeTimeMs")
                        .HasColumnType("float");

                    b.Property<double?>("CacheHitRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("LayerIdx")
                        .HasColumnType("int");

                    b.Property<string>("LayerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LayerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<long?>("ParameterCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Parameters")
                        .HasColumnType("JSON");

                    b.Property<double?>("QuantizationScale")
                        .HasColumnType("float");

                    b.Property<string>("QuantizationType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("QuantizationZeroPoint")
                        .HasColumnType("float");

                    b.Property<string>("TensorDtype")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("float32");

                    b.Property<string>("TensorShape")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<LineString>("WeightsGeometry")
                        .HasColumnType("geometry");

                    b.HasKey("LayerId");

                    b.HasIndex("LayerType")
                        .HasDatabaseName("IX_ModelLayers_LayerType");

                    b.HasIndex("ModelId", "LayerIdx")
                        .HasDatabaseName("IX_ModelLayers_ModelId_LayerIdx");

                    b.ToTable("ModelLayers", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.ModelMetadata", b =>
                {
                    b.Property<int>("MetadataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetadataId"));

                    b.Property<int?>("EmbeddingDimension")
                        .HasColumnType("int");

                    b.Property<string>("License")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxInputLength")
                        .HasColumnType("int");

                    b.Property<int?>("MaxOutputLength")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("PerformanceMetrics")
                        .HasColumnType("JSON");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SupportedModalities")
                        .HasColumnType("JSON");

                    b.Property<string>("SupportedTasks")
                        .HasColumnType("JSON");

                    b.Property<string>("TrainingDataset")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("TrainingDate")
                        .HasColumnType("date");

                    b.HasKey("MetadataId");

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.ToTable("ModelMetadata", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.TensorAtom", b =>
                {
                    b.Property<long>("TensorAtomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TensorAtomId"));

                    b.Property<long>("AtomId")
                        .HasColumnType("bigint");

                    b.Property<string>("AtomType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Geometry>("GeometryFootprint")
                        .HasColumnType("geometry");

                    b.Property<float?>("ImportanceScore")
                        .HasColumnType("real");

                    b.Property<long?>("LayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<Point>("SpatialSignature")
                        .HasColumnType("geometry");

                    b.HasKey("TensorAtomId");

                    b.HasIndex("AtomId");

                    b.HasIndex("LayerId");

                    b.HasIndex("ModelId", "LayerId", "AtomType")
                        .HasDatabaseName("IX_TensorAtoms_Model_Layer_Type");

                    b.ToTable("TensorAtoms", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.TensorAtomCoefficient", b =>
                {
                    b.Property<long>("TensorAtomCoefficientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TensorAtomCoefficientId"));

                    b.Property<float>("Coefficient")
                        .HasColumnType("real");

                    b.Property<long>("ParentLayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("TensorAtomId")
                        .HasColumnType("bigint");

                    b.Property<string>("TensorRole")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("TensorAtomCoefficientId");

                    b.HasIndex("ParentLayerId");

                    b.HasIndex("TensorAtomId", "ParentLayerId", "TensorRole")
                        .HasDatabaseName("IX_TensorAtomCoefficients_Lookup");

                    b.ToTable("TensorAtomCoefficients", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.TextDocument", b =>
                {
                    b.Property<long>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocId"));

                    b.Property<long>("AccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int?>("CharCount")
                        .HasColumnType("int");

                    b.Property<SqlVector<float>?>("GlobalEmbedding")
                        .HasColumnType("VECTOR(768)");

                    b.Property<int?>("GlobalEmbeddingDim")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IngestionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastAccessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("SentimentScore")
                        .HasColumnType("real");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<SqlVector<float>?>("TopicVector")
                        .HasColumnType("VECTOR(100)");

                    b.Property<float?>("Toxicity")
                        .HasColumnType("real");

                    b.Property<int?>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("DocId");

                    b.ToTable("TextDocuments", "dbo");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.TokenVocabulary", b =>
                {
                    b.Property<long>("VocabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VocabId"));

                    b.Property<SqlVector<float>?>("Embedding")
                        .HasColumnType("VECTOR(768)");

                    b.Property<int?>("EmbeddingDim")
                        .HasColumnType("int");

                    b.Property<long>("Frequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<string>("TokenType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VocabId");

                    b.HasIndex("ModelId", "Token")
                        .HasDatabaseName("IX_TokenVocabulary_ModelId_Token");

                    b.HasIndex("ModelId", "TokenId")
                        .IsUnique()
                        .HasDatabaseName("IX_TokenVocabulary_ModelId_TokenId");

                    b.ToTable("TokenVocabulary", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.Video", b =>
                {
                    b.Property<long>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VideoId"));

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Fps")
                        .HasColumnType("int");

                    b.Property<SqlVector<float>?>("GlobalEmbedding")
                        .HasColumnType("VECTOR(768)");

                    b.Property<int?>("GlobalEmbeddingDim")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IngestionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Metadata")
                        .HasColumnType("JSON");

                    b.Property<long>("NumFrames")
                        .HasColumnType("bigint");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("int");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("VideoId");

                    b.HasIndex("IngestionDate")
                        .IsDescending()
                        .HasDatabaseName("IX_Videos_IngestionDate");

                    b.HasIndex("ResolutionWidth", "ResolutionHeight")
                        .HasDatabaseName("IX_Videos_ResolutionWidth_ResolutionHeight");

                    b.ToTable("Videos", "dbo");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.VideoFrame", b =>
                {
                    b.Property<long>("FrameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FrameId"));

                    b.Property<SqlVector<float>?>("FrameEmbedding")
                        .HasColumnType("VECTOR(768)");

                    b.Property<long>("FrameNumber")
                        .HasColumnType("bigint");

                    b.Property<Geometry>("MotionVectors")
                        .HasColumnType("GEOMETRY");

                    b.Property<Geometry>("ObjectRegions")
                        .HasColumnType("GEOMETRY");

                    b.Property<Geometry>("OpticalFlow")
                        .HasColumnType("GEOMETRY");

                    b.Property<byte[]>("PerceptualHash")
                        .HasMaxLength(8)
                        .HasColumnType("varbinary(8)");

                    b.Property<Geometry>("PixelCloud")
                        .HasColumnType("GEOMETRY");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoId")
                        .HasColumnType("bigint");

                    b.HasKey("FrameId");

                    b.HasIndex("VideoId", "FrameNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_VideoFrames_VideoId_FrameNumber");

                    b.HasIndex("VideoId", "TimestampMs")
                        .HasDatabaseName("IX_VideoFrames_VideoId_TimestampMs");

                    b.ToTable("VideoFrames", "dbo");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomEmbedding", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Atom", "Atom")
                        .WithMany("Embeddings")
                        .HasForeignKey("AtomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Entities.Model", "Model")
                        .WithMany("AtomEmbeddings")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Atom");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomEmbeddingComponent", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.AtomEmbedding", "AtomEmbedding")
                        .WithMany("Components")
                        .HasForeignKey("AtomEmbeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtomEmbedding");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomRelation", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Atom", "SourceAtom")
                        .WithMany("SourceRelations")
                        .HasForeignKey("SourceAtomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Entities.Atom", "TargetAtom")
                        .WithMany("TargetRelations")
                        .HasForeignKey("TargetAtomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceAtom");

                    b.Navigation("TargetAtom");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AudioFrame", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.AudioData", "Audio")
                        .WithMany("Frames")
                        .HasForeignKey("AudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audio");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.BillingMultiplier", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.BillingRatePlan", "RatePlan")
                        .WithMany("Multipliers")
                        .HasForeignKey("RatePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RatePlan");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.BillingOperationRate", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.BillingRatePlan", "RatePlan")
                        .WithMany("OperationRates")
                        .HasForeignKey("RatePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RatePlan");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.CachedActivation", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.ModelLayer", "Layer")
                        .WithMany("CachedActivations")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Layer");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.ImagePatch", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Image", "Image")
                        .WithMany("Patches")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.InferenceRequest", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Model", null)
                        .WithMany("InferenceRequests")
                        .HasForeignKey("ModelId");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.InferenceStep", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.InferenceRequest", "InferenceRequest")
                        .WithMany("Steps")
                        .HasForeignKey("InferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InferenceRequest");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.IngestionJobAtom", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Atom", "Atom")
                        .WithMany()
                        .HasForeignKey("AtomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Entities.IngestionJob", "IngestionJob")
                        .WithMany("JobAtoms")
                        .HasForeignKey("IngestionJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atom");

                    b.Navigation("IngestionJob");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.ModelLayer", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Model", "Model")
                        .WithMany("Layers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.ModelMetadata", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Model", "Model")
                        .WithOne("Metadata")
                        .HasForeignKey("Hartonomous.Core.Entities.ModelMetadata", "ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.TensorAtom", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Atom", "Atom")
                        .WithMany("TensorAtoms")
                        .HasForeignKey("AtomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Entities.ModelLayer", "Layer")
                        .WithMany("TensorAtoms")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Hartonomous.Core.Entities.Model", "Model")
                        .WithMany("TensorAtoms")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Atom");

                    b.Navigation("Layer");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.TensorAtomCoefficient", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.ModelLayer", "ParentLayer")
                        .WithMany("TensorAtomCoefficients")
                        .HasForeignKey("ParentLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Entities.TensorAtom", "TensorAtom")
                        .WithMany("Coefficients")
                        .HasForeignKey("TensorAtomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLayer");

                    b.Navigation("TensorAtom");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.TokenVocabulary", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.VideoFrame", b =>
                {
                    b.HasOne("Hartonomous.Core.Entities.Video", "Video")
                        .WithMany("Frames")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.Atom", b =>
                {
                    b.Navigation("Embeddings");

                    b.Navigation("SourceRelations");

                    b.Navigation("TargetRelations");

                    b.Navigation("TensorAtoms");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AtomEmbedding", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.AudioData", b =>
                {
                    b.Navigation("Frames");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.BillingRatePlan", b =>
                {
                    b.Navigation("Multipliers");

                    b.Navigation("OperationRates");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.Image", b =>
                {
                    b.Navigation("Patches");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.InferenceRequest", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.IngestionJob", b =>
                {
                    b.Navigation("JobAtoms");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.Model", b =>
                {
                    b.Navigation("AtomEmbeddings");

                    b.Navigation("InferenceRequests");

                    b.Navigation("Layers");

                    b.Navigation("Metadata");

                    b.Navigation("TensorAtoms");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.ModelLayer", b =>
                {
                    b.Navigation("CachedActivations");

                    b.Navigation("TensorAtomCoefficients");

                    b.Navigation("TensorAtoms");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.TensorAtom", b =>
                {
                    b.Navigation("Coefficients");
                });

            modelBuilder.Entity("Hartonomous.Core.Entities.Video", b =>
                {
                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
