namespace Hartonomous.Api.DTOs.Inference
{
    /// <summary>
    /// Represents the response payload for the synchronous inference endpoint.
    /// </summary>
    public class RunInferenceResponse
    {
        /// <summary>
        /// The resulting embedding generated by the model.
        /// </summary>
        public float[] Embedding { get; set; }
    }
}
